server:
  port: 8081 # Set the server port to 8081
  servlet:
    context-path: /identity
  tomcat:
    redirect-context-root: false

spring:
  datasource:
    url: jdbc:postgresql://aws-0-ap-southeast-1.pooler.supabase.com:6543/postgres?user=postgres.munjhtusfnmmibzgjple&password=1234
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://keycloak.smarthealth.io.vn/realms/SmartHealth
  jpa:
    hibernate:
      ddl-auto: update # Options: create, create-drop, update, validate
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
keycloak:
  admin:
    server-url: https://keycloak.smarthealth.io.vn/
    realm: SmartHealth
    client-id: gateway-local
    username: admin
    password: admin
  realm: SmartHealth
  auth-server-url: https://keycloak.smarthealth.io.vn/
  ssl-required: external
  public-client: true
  bearer-only: false
  client-id: gateway-local
  client-secret: rxqovD1MUxvv46XYlb3dlIULsCsYGtTq
  username: admin
  password: admin123
logging:
  level:
    org.springframework.security: DEBUG
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
    media-type: application/json
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    url: /v3/api-docs


