version: '3.8'

services:
  mysql-db:
    image: mysql:9.2.0
    container_name: mysql_identity
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - smarthealth_network

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    restart: always
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: mysql
      KC_DB_URL: jdbc:mysql://mysql-db:3306/keycloak
      KC_DB_USERNAME: ${MYSQL_USER}
      KC_DB_PASSWORD: ${MYSQL_PASSWORD}
      KC_HTTP_PORT: 8080
      KEYCLOAK_HTTP_PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db
    networks:
      - smarthealth_network
    command: ["start-dev"]

  identity-service:
    build: ./identity-service
    container_name: identity_service
    restart: always
    depends_on:
      - mysql-db
      - keycloak
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/${MYSQL_DATABASE}?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    ports:
      - "8081:8081"
    networks:
      - smarthealth_network

  clinic-web:
    build:
      context: ./web-app/clinic-website
      dockerfile: Dockerfile
    container_name: clinic_web
    restart: always
    depends_on:
      - mysql-db
      - keycloak
      - identity-service
    environment:
      NODE_ENV: production
    ports:
      - "3000:3000"
    networks:
      - smarthealth_network

volumes:
  mysql_data:

networks:
  smarthealth_network:
    driver: bridge
