services:
  postgres-db:
    image: postgres:15
    container_name: postgres_identity
    restart: always
    environment:
      POSTGRES_DB: identity_service
      POSTGRES_USER: identity_admin
      POSTGRES_PASSWORD: MyStrongPassword456@
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - smarthealth_network

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    restart: always
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres-db:5432/identity_service
      KC_DB_USERNAME: identity_admin
      KC_DB_PASSWORD: MyStrongPassword456@
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ready"]
      interval: 1s
      timeout: 5s
      retries: 5
      start_period: 30s
    depends_on:
      - mysql-db
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: 512M
    networks:
      - smarthealth_network
    command: ["start-dev"]

  identity-service:
    image: ${DOCKER_USERNAME}/smarthealth-identity-service:latest
    container_name: identity_service
    restart: always
    depends_on:
      - mysql-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/identity_service
      SPRING_DATASOURCE_USERNAME: identity_admin
      SPRING_DATASOURCE_PASSWORD: MyStrongPassword456@
    ports:
      - "8081:8081"
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: 512M
    networks:
      - smarthealth_network

  clinic-web:
    image: ${DOCKER_USERNAME}/smarthealth-clinic-web:latest
    container_name: clinic_web
    restart: always
    depends_on:
      - mysql-db
      - keycloak
      - identity-service
    environment:
      NODE_ENV: production
    ports:
      - "3000:3000"
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: 256M
    networks:
      - smarthealth_network
  api-gateway:
    image: ${DOCKER_USERNAME}/smarthealth-api-gateway:latest
    container_name: api_gateway
    restart: always
    depends_on:
      - identity-service
    ports:
      - "3001:3001"
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: 256M
    networks:
      - smarthealth_network

volumes:
  mysql_data:

networks:
  smarthealth_network:
    driver: bridge
